# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    - id: terraform_fmt
      args:
        - --args=-diff
    - id: terraform_tflint
    - id: infracost_breakdown
      args:
        - --args=--config-file=./infracost.yml
        - --args=--out-file=infracost-base.json
        - --env-vars=INFRACOST_PARALLELISM=1
        - --env-vars=INFRACOST_SKIP_UPDATE_CHECK=true
